[package]
name = "filter-expr-evaler"
description = "Evaluator for filter expressions."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
documentation = "https://docs.rs/filter-expr"

[dependencies]
filter-expr = { path = "../filter-expr", version = "0.2.0" }

async-trait.workspace = true
thiserror.workspace = true
regex = "1.13.1"
moka = { version = "0.12.16", features = ["sync"] }
anyhow = "1.0.104"

[dev-dependencies]
tokio = { version = "1.53.1", features = ["full"] }
